version: '3'
services:
  flask:
    build: .
    container_name: backend-flask
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - .:/collector
    ports:
      - "5000:5000"
    links:
      - mongodb
    command: python main.py

  mongodb:
    image: mongo:4.4.5-bionic